

cos:  
  key: cos1234
  useTalk: 1
  ip: http://localhost:8000


server:
  
  port: 8000
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  
    
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    password: 4521 
    username: spbooter  
    
  jpa:
    database-platform: com.mycom.blog.config.OracleDialect
    
    open-in-view: true
#    generate-ddl: true
    hibernate:
      ddl-auto: update 
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#      use-new-id-generator-mappings: false #jpa에서 사용하는 넘버링전략을 사용하지 않음
#      
    show-sql: false
    properties:
      hibernate.format_sql: true
  
  security:
    oauth2:
      client:
        registration:
           kakao:
            client-id: 08d4e0306ac821705c50a3083bf85370
            redirect-uri: http://localhost:8000/login/oauth2/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope:  
            - profile,account_email
            client-name: kakao
            
           google:
            redirect-uri: http://localhost:8000/login/oauth2/code/google
            client-id: 378173201540-1f2pka652mudef7odq6bsoqvjbo0iepf.apps.googleusercontent.com
            client-secret: CrcLpyQVvfYZfVas7Dm2Ar_L
            scope:            
            - email
            - profile
           facebook:
            client-id: 2766111593716935
            client-secret: c5189c022aa528bc9d6616a0d78e3e82
            scope:
            - email
            - public_profile
           naver:
            client-id: sq2SqqMajUNe96oInFmP
            client-secret: NrghdZtHAj
            scope:
            - name
            - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8000/login/oauth2/code/naver
         
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # 회원 정보를 json으로 받는데 response를 키값으로 리턴
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

            
  
  jackson:
    serialization:
      fail-on-empty-beans: false

