/*
 * This file is generated by jOOQ.
 */
package com.mycom.jooq.tables;


import com.mycom.jooq.JSpbooter;
import com.mycom.jooq.Keys;
import com.mycom.jooq.tables.records.JBaseEntityRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JBaseEntity extends TableImpl<JBaseEntityRecord> {

    private static final long serialVersionUID = -1781979792;

    /**
     * The reference instance of <code>SPBOOTER.BASE_ENTITY</code>
     */
    public static final JBaseEntity BASE_ENTITY = new JBaseEntity();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<JBaseEntityRecord> getRecordType() {
        return JBaseEntityRecord.class;
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public final TableField<JBaseEntityRecord, Object> ROOMNO = createField(DSL.name("ROOMNO"), org.jooq.impl.SQLDataType.OTHER.defaultValue(org.jooq.impl.DSL.field("", org.jooq.impl.SQLDataType.OTHER)), this, "");

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public final TableField<JBaseEntityRecord, Object> CHAT_USER_USERNO = createField(DSL.name("CHAT_USER_USERNO"), org.jooq.impl.SQLDataType.OTHER.defaultValue(org.jooq.impl.DSL.field("", org.jooq.impl.SQLDataType.OTHER)), this, "");

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public final TableField<JBaseEntityRecord, Object> ME_USERNO = createField(DSL.name("ME_USERNO"), org.jooq.impl.SQLDataType.OTHER.defaultValue(org.jooq.impl.DSL.field("", org.jooq.impl.SQLDataType.OTHER)), this, "");

    /**
     * Create a <code>SPBOOTER.BASE_ENTITY</code> table reference
     */
    public JBaseEntity() {
        this(DSL.name("BASE_ENTITY"), null);
    }

    /**
     * Create an aliased <code>SPBOOTER.BASE_ENTITY</code> table reference
     */
    public JBaseEntity(String alias) {
        this(DSL.name(alias), BASE_ENTITY);
    }

    /**
     * Create an aliased <code>SPBOOTER.BASE_ENTITY</code> table reference
     */
    public JBaseEntity(Name alias) {
        this(alias, BASE_ENTITY);
    }

    private JBaseEntity(Name alias, Table<JBaseEntityRecord> aliased) {
        this(alias, aliased, null);
    }

    private JBaseEntity(Name alias, Table<JBaseEntityRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> JBaseEntity(Table<O> child, ForeignKey<O, JBaseEntityRecord> key) {
        super(child, key, BASE_ENTITY);
    }

    @Override
    public Schema getSchema() {
        return JSpbooter.SPBOOTER;
    }

    @Override
    public UniqueKey<JBaseEntityRecord> getPrimaryKey() {
        return Keys.PK_BASE_ENTITY;
    }

    @Override
    public List<UniqueKey<JBaseEntityRecord>> getKeys() {
        return Arrays.<UniqueKey<JBaseEntityRecord>>asList(Keys.PK_BASE_ENTITY);
    }

    @Override
    public JBaseEntity as(String alias) {
        return new JBaseEntity(DSL.name(alias), this);
    }

    @Override
    public JBaseEntity as(Name alias) {
        return new JBaseEntity(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public JBaseEntity rename(String name) {
        return new JBaseEntity(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public JBaseEntity rename(Name name) {
        return new JBaseEntity(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Object, Object, Object> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
