/*
 * This file is generated by jOOQ.
 */
package com.mycom.jooq.tables;


import com.mycom.jooq.JSpbooter;
import com.mycom.jooq.Keys;
import com.mycom.jooq.tables.records.JBoardRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JBoard extends TableImpl<JBoardRecord> {

    private static final long serialVersionUID = -568163764;

    /**
     * The reference instance of <code>SPBOOTER.BOARD</code>
     */
    public static final JBoard BOARD = new JBoard();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<JBoardRecord> getRecordType() {
        return JBoardRecord.class;
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public final TableField<JBoardRecord, Object> ID = createField(DSL.name("ID"), org.jooq.impl.SQLDataType.OTHER.defaultValue(org.jooq.impl.DSL.field("", org.jooq.impl.SQLDataType.OTHER)), this, "");

    /**
     * The column <code>SPBOOTER.BOARD.CONTENT</code>.
     */
    public final TableField<JBoardRecord, String> CONTENT = createField(DSL.name("CONTENT"), org.jooq.impl.SQLDataType.CLOB.defaultValue(org.jooq.impl.DSL.field("", org.jooq.impl.SQLDataType.CLOB)), this, "");

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public final TableField<JBoardRecord, Object> COUNT = createField(DSL.name("COUNT"), org.jooq.impl.SQLDataType.OTHER.defaultValue(org.jooq.impl.DSL.field("", org.jooq.impl.SQLDataType.OTHER)), this, "");

    /**
     * The column <code>SPBOOTER.BOARD.CREATE_DATE</code>.
     */
    public final TableField<JBoardRecord, Timestamp> CREATE_DATE = createField(DSL.name("CREATE_DATE"), org.jooq.impl.SQLDataType.TIMESTAMP.precision(11).defaultValue(org.jooq.impl.DSL.field("", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public final TableField<JBoardRecord, Object> TITLE = createField(DSL.name("TITLE"), org.jooq.impl.SQLDataType.OTHER.defaultValue(org.jooq.impl.DSL.field("", org.jooq.impl.SQLDataType.OTHER)), this, "");

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public final TableField<JBoardRecord, Object> USERNO = createField(DSL.name("USERNO"), org.jooq.impl.SQLDataType.OTHER.defaultValue(org.jooq.impl.DSL.field("", org.jooq.impl.SQLDataType.OTHER)), this, "");

    /**
     * Create a <code>SPBOOTER.BOARD</code> table reference
     */
    public JBoard() {
        this(DSL.name("BOARD"), null);
    }

    /**
     * Create an aliased <code>SPBOOTER.BOARD</code> table reference
     */
    public JBoard(String alias) {
        this(DSL.name(alias), BOARD);
    }

    /**
     * Create an aliased <code>SPBOOTER.BOARD</code> table reference
     */
    public JBoard(Name alias) {
        this(alias, BOARD);
    }

    private JBoard(Name alias, Table<JBoardRecord> aliased) {
        this(alias, aliased, null);
    }

    private JBoard(Name alias, Table<JBoardRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> JBoard(Table<O> child, ForeignKey<O, JBoardRecord> key) {
        super(child, key, BOARD);
    }

    @Override
    public Schema getSchema() {
        return JSpbooter.SPBOOTER;
    }

    @Override
    public UniqueKey<JBoardRecord> getPrimaryKey() {
        return Keys.PK_BOARD;
    }

    @Override
    public List<UniqueKey<JBoardRecord>> getKeys() {
        return Arrays.<UniqueKey<JBoardRecord>>asList(Keys.PK_BOARD);
    }

    @Override
    public JBoard as(String alias) {
        return new JBoard(DSL.name(alias), this);
    }

    @Override
    public JBoard as(Name alias) {
        return new JBoard(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public JBoard rename(String name) {
        return new JBoard(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public JBoard rename(Name name) {
        return new JBoard(name, null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<Object, String, Object, Timestamp, Object, Object> fieldsRow() {
        return (Row6) super.fieldsRow();
    }
}
