/*
 * This file is generated by jOOQ.
 */
package com.mycom.jooq.tables;


import com.mycom.jooq.JSpbooter;
import com.mycom.jooq.Keys;
import com.mycom.jooq.tables.records.JChatMessageRoomRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row5;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JChatMessageRoom extends TableImpl<JChatMessageRoomRecord> {

    private static final long serialVersionUID = -1360469553;

    /**
     * The reference instance of <code>SPBOOTER.CHAT_MESSAGE_ROOM</code>
     */
    public static final JChatMessageRoom CHAT_MESSAGE_ROOM = new JChatMessageRoom();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<JChatMessageRoomRecord> getRecordType() {
        return JChatMessageRoomRecord.class;
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public final TableField<JChatMessageRoomRecord, Object> MESSAGENO = createField(DSL.name("MESSAGENO"), org.jooq.impl.SQLDataType.OTHER.defaultValue(org.jooq.impl.DSL.field("", org.jooq.impl.SQLDataType.OTHER)), this, "");

    /**
     * The column <code>SPBOOTER.CHAT_MESSAGE_ROOM.CREATE_DATE</code>.
     */
    public final TableField<JChatMessageRoomRecord, Timestamp> CREATE_DATE = createField(DSL.name("CREATE_DATE"), org.jooq.impl.SQLDataType.TIMESTAMP.precision(11).defaultValue(org.jooq.impl.DSL.field("", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public final TableField<JChatMessageRoomRecord, Object> TEXT = createField(DSL.name("TEXT"), org.jooq.impl.SQLDataType.OTHER.defaultValue(org.jooq.impl.DSL.field("", org.jooq.impl.SQLDataType.OTHER)), this, "");

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public final TableField<JChatMessageRoomRecord, Object> USERNO = createField(DSL.name("USERNO"), org.jooq.impl.SQLDataType.OTHER.defaultValue(org.jooq.impl.DSL.field("", org.jooq.impl.SQLDataType.OTHER)), this, "");

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public final TableField<JChatMessageRoomRecord, Object> ROOMNO = createField(DSL.name("ROOMNO"), org.jooq.impl.SQLDataType.OTHER.defaultValue(org.jooq.impl.DSL.field("", org.jooq.impl.SQLDataType.OTHER)), this, "");

    /**
     * Create a <code>SPBOOTER.CHAT_MESSAGE_ROOM</code> table reference
     */
    public JChatMessageRoom() {
        this(DSL.name("CHAT_MESSAGE_ROOM"), null);
    }

    /**
     * Create an aliased <code>SPBOOTER.CHAT_MESSAGE_ROOM</code> table reference
     */
    public JChatMessageRoom(String alias) {
        this(DSL.name(alias), CHAT_MESSAGE_ROOM);
    }

    /**
     * Create an aliased <code>SPBOOTER.CHAT_MESSAGE_ROOM</code> table reference
     */
    public JChatMessageRoom(Name alias) {
        this(alias, CHAT_MESSAGE_ROOM);
    }

    private JChatMessageRoom(Name alias, Table<JChatMessageRoomRecord> aliased) {
        this(alias, aliased, null);
    }

    private JChatMessageRoom(Name alias, Table<JChatMessageRoomRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> JChatMessageRoom(Table<O> child, ForeignKey<O, JChatMessageRoomRecord> key) {
        super(child, key, CHAT_MESSAGE_ROOM);
    }

    @Override
    public Schema getSchema() {
        return JSpbooter.SPBOOTER;
    }

    @Override
    public UniqueKey<JChatMessageRoomRecord> getPrimaryKey() {
        return Keys.PK_CHAT_MESSAGE_ROOM;
    }

    @Override
    public List<UniqueKey<JChatMessageRoomRecord>> getKeys() {
        return Arrays.<UniqueKey<JChatMessageRoomRecord>>asList(Keys.PK_CHAT_MESSAGE_ROOM);
    }

    @Override
    public JChatMessageRoom as(String alias) {
        return new JChatMessageRoom(DSL.name(alias), this);
    }

    @Override
    public JChatMessageRoom as(Name alias) {
        return new JChatMessageRoom(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public JChatMessageRoom rename(String name) {
        return new JChatMessageRoom(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public JChatMessageRoom rename(Name name) {
        return new JChatMessageRoom(name, null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<Object, Timestamp, Object, Object, Object> fieldsRow() {
        return (Row5) super.fieldsRow();
    }
}
