/*
 * This file is generated by jOOQ.
 */
package com.mycom.jooq.tables;


import com.mycom.jooq.JSpbooter;
import com.mycom.jooq.Keys;
import com.mycom.jooq.tables.records.JChatRoomGuideRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JChatRoomGuide extends TableImpl<JChatRoomGuideRecord> {

    private static final long serialVersionUID = -2016007256;

    /**
     * The reference instance of <code>SPBOOTER.CHAT_ROOM_GUIDE</code>
     */
    public static final JChatRoomGuide CHAT_ROOM_GUIDE = new JChatRoomGuide();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<JChatRoomGuideRecord> getRecordType() {
        return JChatRoomGuideRecord.class;
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public final TableField<JChatRoomGuideRecord, Object> NO = createField(DSL.name("NO"), org.jooq.impl.SQLDataType.OTHER.defaultValue(org.jooq.impl.DSL.field("", org.jooq.impl.SQLDataType.OTHER)), this, "");

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public final TableField<JChatRoomGuideRecord, Object> CHAT_ROOM_ROOMNO = createField(DSL.name("CHAT_ROOM_ROOMNO"), org.jooq.impl.SQLDataType.OTHER.defaultValue(org.jooq.impl.DSL.field("", org.jooq.impl.SQLDataType.OTHER)), this, "");

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public final TableField<JChatRoomGuideRecord, Object> ME_USERNO = createField(DSL.name("ME_USERNO"), org.jooq.impl.SQLDataType.OTHER.defaultValue(org.jooq.impl.DSL.field("", org.jooq.impl.SQLDataType.OTHER)), this, "");

    /**
     * Create a <code>SPBOOTER.CHAT_ROOM_GUIDE</code> table reference
     */
    public JChatRoomGuide() {
        this(DSL.name("CHAT_ROOM_GUIDE"), null);
    }

    /**
     * Create an aliased <code>SPBOOTER.CHAT_ROOM_GUIDE</code> table reference
     */
    public JChatRoomGuide(String alias) {
        this(DSL.name(alias), CHAT_ROOM_GUIDE);
    }

    /**
     * Create an aliased <code>SPBOOTER.CHAT_ROOM_GUIDE</code> table reference
     */
    public JChatRoomGuide(Name alias) {
        this(alias, CHAT_ROOM_GUIDE);
    }

    private JChatRoomGuide(Name alias, Table<JChatRoomGuideRecord> aliased) {
        this(alias, aliased, null);
    }

    private JChatRoomGuide(Name alias, Table<JChatRoomGuideRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> JChatRoomGuide(Table<O> child, ForeignKey<O, JChatRoomGuideRecord> key) {
        super(child, key, CHAT_ROOM_GUIDE);
    }

    @Override
    public Schema getSchema() {
        return JSpbooter.SPBOOTER;
    }

    @Override
    public UniqueKey<JChatRoomGuideRecord> getPrimaryKey() {
        return Keys.PK_CHAT_ROOM_GUIDE;
    }

    @Override
    public List<UniqueKey<JChatRoomGuideRecord>> getKeys() {
        return Arrays.<UniqueKey<JChatRoomGuideRecord>>asList(Keys.PK_CHAT_ROOM_GUIDE);
    }

    @Override
    public JChatRoomGuide as(String alias) {
        return new JChatRoomGuide(DSL.name(alias), this);
    }

    @Override
    public JChatRoomGuide as(Name alias) {
        return new JChatRoomGuide(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public JChatRoomGuide rename(String name) {
        return new JChatRoomGuide(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public JChatRoomGuide rename(Name name) {
        return new JChatRoomGuide(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Object, Object, Object> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
