/*
 * This file is generated by jOOQ.
 */
package com.mycom.jooq.tables;


import com.mycom.jooq.JSpbooter;
import com.mycom.jooq.Keys;
import com.mycom.jooq.tables.records.JChatRoomRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JChatRoom extends TableImpl<JChatRoomRecord> {

    private static final long serialVersionUID = 1508087983;

    /**
     * The reference instance of <code>SPBOOTER.CHAT_ROOM</code>
     */
    public static final JChatRoom CHAT_ROOM = new JChatRoom();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<JChatRoomRecord> getRecordType() {
        return JChatRoomRecord.class;
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public final TableField<JChatRoomRecord, Object> ROOMNO = createField(DSL.name("ROOMNO"), org.jooq.impl.SQLDataType.OTHER.defaultValue(org.jooq.impl.DSL.field("", org.jooq.impl.SQLDataType.OTHER)), this, "");

    /**
     * The column <code>SPBOOTER.CHAT_ROOM.CREATE_DATE</code>.
     */
    public final TableField<JChatRoomRecord, Timestamp> CREATE_DATE = createField(DSL.name("CREATE_DATE"), org.jooq.impl.SQLDataType.TIMESTAMP.precision(11).defaultValue(org.jooq.impl.DSL.field("", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public final TableField<JChatRoomRecord, Object> TOPIC = createField(DSL.name("TOPIC"), org.jooq.impl.SQLDataType.OTHER.defaultValue(org.jooq.impl.DSL.field("", org.jooq.impl.SQLDataType.OTHER)), this, "");

    /**
     * Create a <code>SPBOOTER.CHAT_ROOM</code> table reference
     */
    public JChatRoom() {
        this(DSL.name("CHAT_ROOM"), null);
    }

    /**
     * Create an aliased <code>SPBOOTER.CHAT_ROOM</code> table reference
     */
    public JChatRoom(String alias) {
        this(DSL.name(alias), CHAT_ROOM);
    }

    /**
     * Create an aliased <code>SPBOOTER.CHAT_ROOM</code> table reference
     */
    public JChatRoom(Name alias) {
        this(alias, CHAT_ROOM);
    }

    private JChatRoom(Name alias, Table<JChatRoomRecord> aliased) {
        this(alias, aliased, null);
    }

    private JChatRoom(Name alias, Table<JChatRoomRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> JChatRoom(Table<O> child, ForeignKey<O, JChatRoomRecord> key) {
        super(child, key, CHAT_ROOM);
    }

    @Override
    public Schema getSchema() {
        return JSpbooter.SPBOOTER;
    }

    @Override
    public UniqueKey<JChatRoomRecord> getPrimaryKey() {
        return Keys.PK_CHAT_ROOM;
    }

    @Override
    public List<UniqueKey<JChatRoomRecord>> getKeys() {
        return Arrays.<UniqueKey<JChatRoomRecord>>asList(Keys.PK_CHAT_ROOM);
    }

    @Override
    public JChatRoom as(String alias) {
        return new JChatRoom(DSL.name(alias), this);
    }

    @Override
    public JChatRoom as(Name alias) {
        return new JChatRoom(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public JChatRoom rename(String name) {
        return new JChatRoom(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public JChatRoom rename(Name name) {
        return new JChatRoom(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Object, Timestamp, Object> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
