/*
 * This file is generated by jOOQ.
 */
package com.mycom.jooq.tables;


import com.mycom.jooq.JSpbooter;
import com.mycom.jooq.Keys;
import com.mycom.jooq.tables.records.JNoticeRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row5;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JNotice extends TableImpl<JNoticeRecord> {

    private static final long serialVersionUID = 2079886098;

    /**
     * The reference instance of <code>SPBOOTER.NOTICE</code>
     */
    public static final JNotice NOTICE = new JNotice();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<JNoticeRecord> getRecordType() {
        return JNoticeRecord.class;
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public final TableField<JNoticeRecord, Object> NO = createField(DSL.name("NO"), org.jooq.impl.SQLDataType.OTHER.defaultValue(org.jooq.impl.DSL.field("", org.jooq.impl.SQLDataType.OTHER)), this, "");

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public final TableField<JNoticeRecord, Object> CONTENTS = createField(DSL.name("CONTENTS"), org.jooq.impl.SQLDataType.OTHER.defaultValue(org.jooq.impl.DSL.field("", org.jooq.impl.SQLDataType.OTHER)), this, "");

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public final TableField<JNoticeRecord, Object> NAME = createField(DSL.name("NAME"), org.jooq.impl.SQLDataType.OTHER.defaultValue(org.jooq.impl.DSL.field("", org.jooq.impl.SQLDataType.OTHER)), this, "");

    /**
     * The column <code>SPBOOTER.NOTICE.REGDATE</code>.
     */
    public final TableField<JNoticeRecord, Timestamp> REGDATE = createField(DSL.name("REGDATE"), org.jooq.impl.SQLDataType.TIMESTAMP.precision(11).defaultValue(org.jooq.impl.DSL.field("", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public final TableField<JNoticeRecord, Object> TITLE = createField(DSL.name("TITLE"), org.jooq.impl.SQLDataType.OTHER.defaultValue(org.jooq.impl.DSL.field("", org.jooq.impl.SQLDataType.OTHER)), this, "");

    /**
     * Create a <code>SPBOOTER.NOTICE</code> table reference
     */
    public JNotice() {
        this(DSL.name("NOTICE"), null);
    }

    /**
     * Create an aliased <code>SPBOOTER.NOTICE</code> table reference
     */
    public JNotice(String alias) {
        this(DSL.name(alias), NOTICE);
    }

    /**
     * Create an aliased <code>SPBOOTER.NOTICE</code> table reference
     */
    public JNotice(Name alias) {
        this(alias, NOTICE);
    }

    private JNotice(Name alias, Table<JNoticeRecord> aliased) {
        this(alias, aliased, null);
    }

    private JNotice(Name alias, Table<JNoticeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> JNotice(Table<O> child, ForeignKey<O, JNoticeRecord> key) {
        super(child, key, NOTICE);
    }

    @Override
    public Schema getSchema() {
        return JSpbooter.SPBOOTER;
    }

    @Override
    public UniqueKey<JNoticeRecord> getPrimaryKey() {
        return Keys.PK_NOTICE;
    }

    @Override
    public List<UniqueKey<JNoticeRecord>> getKeys() {
        return Arrays.<UniqueKey<JNoticeRecord>>asList(Keys.PK_NOTICE);
    }

    @Override
    public JNotice as(String alias) {
        return new JNotice(DSL.name(alias), this);
    }

    @Override
    public JNotice as(Name alias) {
        return new JNotice(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public JNotice rename(String name) {
        return new JNotice(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public JNotice rename(Name name) {
        return new JNotice(name, null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<Object, Object, Object, Timestamp, Object> fieldsRow() {
        return (Row5) super.fieldsRow();
    }
}
