/*
 * This file is generated by jOOQ.
 */
package com.mycom.jooq.tables;


import com.mycom.jooq.JSpbooter;
import com.mycom.jooq.Keys;
import com.mycom.jooq.tables.records.JPaymentRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row5;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JPayment extends TableImpl<JPaymentRecord> {

    private static final long serialVersionUID = -1155720575;

    /**
     * The reference instance of <code>SPBOOTER.PAYMENT</code>
     */
    public static final JPayment PAYMENT = new JPayment();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<JPaymentRecord> getRecordType() {
        return JPaymentRecord.class;
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public final TableField<JPaymentRecord, Object> PAYMENTNO = createField(DSL.name("PAYMENTNO"), org.jooq.impl.SQLDataType.OTHER.defaultValue(org.jooq.impl.DSL.field("", org.jooq.impl.SQLDataType.OTHER)), this, "");

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public final TableField<JPaymentRecord, Object> PAY = createField(DSL.name("PAY"), org.jooq.impl.SQLDataType.OTHER.defaultValue(org.jooq.impl.DSL.field("", org.jooq.impl.SQLDataType.OTHER)), this, "");

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public final TableField<JPaymentRecord, Object> PAYTYPE = createField(DSL.name("PAYTYPE"), org.jooq.impl.SQLDataType.OTHER.defaultValue(org.jooq.impl.DSL.field("", org.jooq.impl.SQLDataType.OTHER)), this, "");

    /**
     * The column <code>SPBOOTER.PAYMENT.REGTIME</code>.
     */
    public final TableField<JPaymentRecord, Timestamp> REGTIME = createField(DSL.name("REGTIME"), org.jooq.impl.SQLDataType.TIMESTAMP.precision(11).defaultValue(org.jooq.impl.DSL.field("", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public final TableField<JPaymentRecord, Object> USERNO = createField(DSL.name("USERNO"), org.jooq.impl.SQLDataType.OTHER.defaultValue(org.jooq.impl.DSL.field("", org.jooq.impl.SQLDataType.OTHER)), this, "");

    /**
     * Create a <code>SPBOOTER.PAYMENT</code> table reference
     */
    public JPayment() {
        this(DSL.name("PAYMENT"), null);
    }

    /**
     * Create an aliased <code>SPBOOTER.PAYMENT</code> table reference
     */
    public JPayment(String alias) {
        this(DSL.name(alias), PAYMENT);
    }

    /**
     * Create an aliased <code>SPBOOTER.PAYMENT</code> table reference
     */
    public JPayment(Name alias) {
        this(alias, PAYMENT);
    }

    private JPayment(Name alias, Table<JPaymentRecord> aliased) {
        this(alias, aliased, null);
    }

    private JPayment(Name alias, Table<JPaymentRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> JPayment(Table<O> child, ForeignKey<O, JPaymentRecord> key) {
        super(child, key, PAYMENT);
    }

    @Override
    public Schema getSchema() {
        return JSpbooter.SPBOOTER;
    }

    @Override
    public UniqueKey<JPaymentRecord> getPrimaryKey() {
        return Keys.PK_PAYMENT;
    }

    @Override
    public List<UniqueKey<JPaymentRecord>> getKeys() {
        return Arrays.<UniqueKey<JPaymentRecord>>asList(Keys.PK_PAYMENT);
    }

    @Override
    public JPayment as(String alias) {
        return new JPayment(DSL.name(alias), this);
    }

    @Override
    public JPayment as(Name alias) {
        return new JPayment(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public JPayment rename(String name) {
        return new JPayment(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public JPayment rename(Name name) {
        return new JPayment(name, null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<Object, Object, Object, Timestamp, Object> fieldsRow() {
        return (Row5) super.fieldsRow();
    }
}
