/*
 * This file is generated by jOOQ.
 */
package com.mycom.jooq.tables;


import com.mycom.jooq.JSpbooter;
import com.mycom.jooq.Keys;
import com.mycom.jooq.tables.records.JShopRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JShop extends TableImpl<JShopRecord> {

    private static final long serialVersionUID = 1905197709;

    /**
     * The reference instance of <code>SPBOOTER.SHOP</code>
     */
    public static final JShop SHOP = new JShop();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<JShopRecord> getRecordType() {
        return JShopRecord.class;
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public final TableField<JShopRecord, Object> NO = createField(DSL.name("NO"), org.jooq.impl.SQLDataType.OTHER.defaultValue(org.jooq.impl.DSL.field("", org.jooq.impl.SQLDataType.OTHER)), this, "");

    /**
     * The column <code>SPBOOTER.SHOP.CREATE_DATE</code>.
     */
    public final TableField<JShopRecord, Timestamp> CREATE_DATE = createField(DSL.name("CREATE_DATE"), org.jooq.impl.SQLDataType.TIMESTAMP.precision(11).defaultValue(org.jooq.impl.DSL.field("", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public final TableField<JShopRecord, Object> ITEM_TYPE = createField(DSL.name("ITEM_TYPE"), org.jooq.impl.SQLDataType.OTHER.defaultValue(org.jooq.impl.DSL.field("", org.jooq.impl.SQLDataType.OTHER)), this, "");

    /**
     * Create a <code>SPBOOTER.SHOP</code> table reference
     */
    public JShop() {
        this(DSL.name("SHOP"), null);
    }

    /**
     * Create an aliased <code>SPBOOTER.SHOP</code> table reference
     */
    public JShop(String alias) {
        this(DSL.name(alias), SHOP);
    }

    /**
     * Create an aliased <code>SPBOOTER.SHOP</code> table reference
     */
    public JShop(Name alias) {
        this(alias, SHOP);
    }

    private JShop(Name alias, Table<JShopRecord> aliased) {
        this(alias, aliased, null);
    }

    private JShop(Name alias, Table<JShopRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> JShop(Table<O> child, ForeignKey<O, JShopRecord> key) {
        super(child, key, SHOP);
    }

    @Override
    public Schema getSchema() {
        return JSpbooter.SPBOOTER;
    }

    @Override
    public UniqueKey<JShopRecord> getPrimaryKey() {
        return Keys.PK_SHOP;
    }

    @Override
    public List<UniqueKey<JShopRecord>> getKeys() {
        return Arrays.<UniqueKey<JShopRecord>>asList(Keys.PK_SHOP);
    }

    @Override
    public JShop as(String alias) {
        return new JShop(DSL.name(alias), this);
    }

    @Override
    public JShop as(Name alias) {
        return new JShop(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public JShop rename(String name) {
        return new JShop(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public JShop rename(Name name) {
        return new JShop(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Object, Timestamp, Object> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
