/*
 * This file is generated by jOOQ.
 */
package com.mycom.jooq;


import com.mycom.jooq.tables.JBaseEntity;
import com.mycom.jooq.tables.JBoard;
import com.mycom.jooq.tables.JBook;
import com.mycom.jooq.tables.JBookStore;
import com.mycom.jooq.tables.JChatMessageRoom;
import com.mycom.jooq.tables.JChatRoom;
import com.mycom.jooq.tables.JFriend;
import com.mycom.jooq.tables.JLocation;
import com.mycom.jooq.tables.JReply;
import com.mycom.jooq.tables.JUser1;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in SPBOOTER
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>SPBOOTER.BASE_ENTITY</code>.
     */
    public static final JBaseEntity BASE_ENTITY = JBaseEntity.BASE_ENTITY;

    /**
     * The table <code>SPBOOTER.BOARD</code>.
     */
    public static final JBoard BOARD = JBoard.BOARD;

    /**
     * The table <code>SPBOOTER.BOOK</code>.
     */
    public static final JBook BOOK = JBook.BOOK;

    /**
     * The table <code>SPBOOTER.BOOK_STORE</code>.
     */
    public static final JBookStore BOOK_STORE = JBookStore.BOOK_STORE;

    /**
     * The table <code>SPBOOTER.CHAT_MESSAGE_ROOM</code>.
     */
    public static final JChatMessageRoom CHAT_MESSAGE_ROOM = JChatMessageRoom.CHAT_MESSAGE_ROOM;

    /**
     * The table <code>SPBOOTER.CHAT_ROOM</code>.
     */
    public static final JChatRoom CHAT_ROOM = JChatRoom.CHAT_ROOM;

    /**
     * The table <code>SPBOOTER.FRIEND</code>.
     */
    public static final JFriend FRIEND = JFriend.FRIEND;

    /**
     * The table <code>SPBOOTER.LOCATION</code>.
     */
    public static final JLocation LOCATION = JLocation.LOCATION;

    /**
     * The table <code>SPBOOTER.REPLY</code>.
     */
    public static final JReply REPLY = JReply.REPLY;

    /**
     * The table <code>SPBOOTER.USER1</code>.
     */
    public static final JUser1 USER1 = JUser1.USER1;
}
