/*
 * This file is generated by jOOQ.
 */
package com.mycom.jooq;


import com.mycom.jooq.tables.JBoard;
import com.mycom.jooq.tables.JChatMessageRoom;
import com.mycom.jooq.tables.JChatRoom;
import com.mycom.jooq.tables.JChatRoomGuide;
import com.mycom.jooq.tables.JFriend;
import com.mycom.jooq.tables.JItem;
import com.mycom.jooq.tables.JLocation;
import com.mycom.jooq.tables.JNotice;
import com.mycom.jooq.tables.JPayment;
import com.mycom.jooq.tables.JReply;
import com.mycom.jooq.tables.JShop;
import com.mycom.jooq.tables.JUser1;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in SPBOOTER
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>SPBOOTER.BOARD</code>.
     */
    public static final JBoard BOARD = JBoard.BOARD;

    /**
     * The table <code>SPBOOTER.CHAT_MESSAGE_ROOM</code>.
     */
    public static final JChatMessageRoom CHAT_MESSAGE_ROOM = JChatMessageRoom.CHAT_MESSAGE_ROOM;

    /**
     * The table <code>SPBOOTER.CHAT_ROOM</code>.
     */
    public static final JChatRoom CHAT_ROOM = JChatRoom.CHAT_ROOM;

    /**
     * The table <code>SPBOOTER.CHAT_ROOM_GUIDE</code>.
     */
    public static final JChatRoomGuide CHAT_ROOM_GUIDE = JChatRoomGuide.CHAT_ROOM_GUIDE;

    /**
     * The table <code>SPBOOTER.FRIEND</code>.
     */
    public static final JFriend FRIEND = JFriend.FRIEND;

    /**
     * The table <code>SPBOOTER.ITEM</code>.
     */
    public static final JItem ITEM = JItem.ITEM;

    /**
     * The table <code>SPBOOTER.LOCATION</code>.
     */
    public static final JLocation LOCATION = JLocation.LOCATION;

    /**
     * The table <code>SPBOOTER.NOTICE</code>.
     */
    public static final JNotice NOTICE = JNotice.NOTICE;

    /**
     * The table <code>SPBOOTER.PAYMENT</code>.
     */
    public static final JPayment PAYMENT = JPayment.PAYMENT;

    /**
     * The table <code>SPBOOTER.REPLY</code>.
     */
    public static final JReply REPLY = JReply.REPLY;

    /**
     * The table <code>SPBOOTER.SHOP</code>.
     */
    public static final JShop SHOP = JShop.SHOP;

    /**
     * The table <code>SPBOOTER.USER1</code>.
     */
    public static final JUser1 USER1 = JUser1.USER1;
}
