<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ include file="../../layout/header.jsp"%>
<body>
	<div class="myContainer">
		<div class="d-flex">
			<button id="searchBtn" class="ml-auto btn btn-success">검색</button>
		</div>
		<div id="searchBody">
			<table>
				<thead>
					<tr>
					<th><div><input><br><i class="fas fa-ellipsis-v"></i><br><input></div></th>
					<th><div><input></div></th>
					<th><div><input></div></th>
					<th><div><input></div></th>
					<th><div><input></div></th>
					<th><div><input><br><i class="fas fa-ellipsis-v"></i><br><input></div></th>
					<th><div><select><option>남</option><option>여</option></select></div></th>
					<th><div><input></div></th>
					<th><div><input><br><i class="fas fa-ellipsis-v"></i><br><input></div></th>
					<th><div><input><br><i class="fas fa-ellipsis-v"></i><br><input></div></th>
					<th><div><input><br><i class="fas fa-ellipsis-v"></i><br><input></div></th>
					<th><div><input type="date"><br><i class="fas fa-ellipsis-v"></i><br><input type="date"></div></th>
					<th><div><input></div></th>
					<th><div><select><option>user</option><option>admin</option></select></div></th>
					</tr>
				</thead>
				<thead>
					<tr>
						<th>회원번호</th>
						<th>이름</th>
						<th>아이디</th>
						<th>비밀번호</th>
						<th>닉네임</th>
						<th>나이</th>
						<th>성별</th>
						<th>이메일</th>
						<th>총결제금액</th>
						<th>코인</th>
						<th>이용가능토크</th>
						<th>회원가입일</th>
						<th>활동지역</th>
						<th>권한</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>회원번호</td>
						<td>이름</td>
						<td>아이디</td>
						<td>비밀번호</td>
						<td>닉네임</td>
						<td>나이</td>
						<td>성별</td>
						<td>이메일</td>
						<td>총결제금액</td>
						<td>코인</td>
						<td>이용가능토크</td>
						<td>회원가입일</td>
						<td>활동지역</td>
						<td>권한</td>
					</tr>
					<tr>
						<td>회원번호</td>
						<td>이름</td>
						<td>아이디</td>
						<td>비밀번호</td>
						<td>닉네임</td>
						<td>나이</td>
						<td>성별</td>
						<td>이메일</td>
						<td>총결제금액</td>
						<td>코인</td>
						<td>이용가능토크</td>
						<td>회원가입일</td>
						<td>활동지역</td>
						<td>권한</td>
					</tr>
					<tr>
						<td>회원번호</td>
						<td>이름</td>
						<td>아이디</td>
						<td>비밀번호</td>
						<td>닉네임</td>
						<td>나이</td>
						<td>성별</td>
						<td>이메일</td>
						<td>총결제금액</td>
						<td>코인</td>
						<td>이용가능토크</td>
						<td>회원가입일</td>
						<td>활동지역</td>
						<td>권한</td>
					</tr>
					<tr>
						<td>회원번호</td>
						<td>이름</td>
						<td>아이디</td>
						<td>비밀번호</td>
						<td>닉네임</td>
						<td>나이</td>
						<td>성별</td>
						<td>이메일</td>
						<td>총결제금액</td>
						<td>코인</td>
						<td>이용가능토크</td>
						<td>회원가입일</td>
						<td>활동지역</td>
						<td>권한</td>
					</tr>
					<tr>
						<td>회원번호</td>
						<td>이름</td>
						<td>아이디</td>
						<td>비밀번호</td>
						<td>닉네임</td>
						<td>나이</td>
						<td>성별</td>
						<td>이메일</td>
						<td>총결제금액</td>
						<td>코인</td>
						<td>이용가능토크</td>
						<td>회원가입일</td>
						<td>활동지역</td>
						<td>권한</td>
					</tr>
					<tr>
						<td>회원번호</td>
						<td>이름</td>
						<td>아이디</td>
						<td>비밀번호</td>
						<td>닉네임</td>
						<td>나이</td>
						<td>성별</td>
						<td>이메일</td>
						<td>총결제금액</td>
						<td>코인</td>
						<td>이용가능토크</td>
						<td>회원가입일</td>
						<td>활동지역</td>
						<td>권한</td>
					</tr>
					<tr>
						<td>회원번호</td>
						<td>이름</td>
						<td>아이디</td>
						<td>비밀번호</td>
						<td>닉네임</td>
						<td>나이</td>
						<td>성별</td>
						<td>이메일</td>
						<td>총결제금액</td>
						<td>코인</td>
						<td>이용가능토크</td>
						<td>회원가입일</td>
						<td>활동지역</td>
						<td>권한</td>
					</tr>
					<tr>
						<td>회원번호</td>
						<td>이름</td>
						<td>아이디</td>
						<td>비밀번호</td>
						<td>닉네임</td>
						<td>나이</td>
						<td>성별</td>
						<td>이메일</td>
						<td>총결제금액</td>
						<td>코인</td>
						<td>이용가능토크</td>
						<td>회원가입일</td>
						<td>활동지역</td>
						<td>권한</td>
					</tr>
					<tr>
						<td>회원번호</td>
						<td>이름</td>
						<td>아이디</td>
						<td>비밀번호</td>
						<td>닉네임</td>
						<td>나이</td>
						<td>성별</td>
						<td>이메일</td>
						<td>총결제금액</td>
						<td>코인</td>
						<td>이용가능토크</td>
						<td>회원가입일</td>
						<td>활동지역</td>
						<td>권한</td>
					</tr>
					<tr>
						<td>회원번호</td>
						<td>이름</td>
						<td>아이디</td>
						<td>비밀번호</td>
						<td>닉네임</td>
						<td>나이</td>
						<td>성별</td>
						<td>이메일</td>
						<td>총결제금액</td>
						<td>코인</td>
						<td>이용가능토크</td>
						<td>회원가입일</td>
						<td>활동지역</td>
						<td>권한</td>
					</tr>
					<tr>
						<td>회원번호</td>
						<td>이름</td>
						<td>아이디</td>
						<td>비밀번호</td>
						<td>닉네임</td>
						<td>나이</td>
						<td>성별</td>
						<td>이메일</td>
						<td>총결제금액</td>
						<td>코인</td>
						<td>이용가능토크</td>
						<td>회원가입일</td>
						<td>활동지역</td>
						<td>권한</td>
					</tr>
					<tr>
						<td>회원번호</td>
						<td>이름</td>
						<td>아이디</td>
						<td>비밀번호</td>
						<td>닉네임</td>
						<td>나이</td>
						<td>성별</td>
						<td>이메일</td>
						<td>총결제금액</td>
						<td>코인</td>
						<td>이용가능토크</td>
						<td>회원가입일</td>
						<td>활동지역</td>
						<td>권한</td>
					</tr>
					<tr>
						<td>회원번호</td>
						<td>이름</td>
						<td>아이디</td>
						<td>비밀번호</td>
						<td>닉네임</td>
						<td>나이</td>
						<td>성별</td>
						<td>이메일</td>
						<td>총결제금액</td>
						<td>코인</td>
						<td>이용가능토크</td>
						<td>회원가입일</td>
						<td>활동지역</td>
						<td>권한</td>
					</tr>
					<tr>
						<td>회원번호</td>
						<td>이름</td>
						<td>아이디</td>
						<td>비밀번호</td>
						<td>닉네임</td>
						<td>나이</td>
						<td>성별</td>
						<td>이메일</td>
						<td>총결제금액</td>
						<td>코인</td>
						<td>이용가능토크</td>
						<td>회원가입일</td>
						<td>활동지역</td>
						<td>권한</td>
					</tr>
					<tr>
						<td>회원번호</td>
						<td>이름</td>
						<td>아이디</td>
						<td>비밀번호</td>
						<td>닉네임</td>
						<td>나이</td>
						<td>성별</td>
						<td>이메일</td>
						<td>총결제금액</td>
						<td>코인</td>
						<td>이용가능토크</td>
						<td>회원가입일</td>
						<td>활동지역</td>
						<td>권한</td>
					</tr>
					<tr>
						<td>회원번호</td>
						<td>이름</td>
						<td>아이디</td>
						<td>비밀번호</td>
						<td>닉네임</td>
						<td>나이</td>
						<td>성별</td>
						<td>이메일</td>
						<td>총결제금액</td>
						<td>코인</td>
						<td>이용가능토크</td>
						<td>회원가입일</td>
						<td>활동지역</td>
						<td>권한</td>
					</tr>
					<tr>
						<td>회원번호</td>
						<td>이름</td>
						<td>아이디</td>
						<td>비밀번호</td>
						<td>닉네임</td>
						<td>나이</td>
						<td>성별</td>
						<td>이메일</td>
						<td>총결제금액</td>
						<td>코인</td>
						<td>이용가능토크</td>
						<td>회원가입일</td>
						<td>활동지역</td>
						<td>권한</td>
					</tr>
					<tr>
						<td>회원번호</td>
						<td>이름</td>
						<td>아이디</td>
						<td>비밀번호</td>
						<td>닉네임</td>
						<td>나이</td>
						<td>성별</td>
						<td>이메일</td>
						<td>총결제금액</td>
						<td>코인</td>
						<td>이용가능토크</td>
						<td>회원가입일</td>
						<td>활동지역</td>
						<td>권한</td>
					</tr>
					<tr>
						<td>회원번호</td>
						<td>이름</td>
						<td>아이디</td>
						<td>비밀번호</td>
						<td>닉네임</td>
						<td>나이</td>
						<td>성별</td>
						<td>이메일</td>
						<td>총결제금액</td>
						<td>코인</td>
						<td>이용가능토크</td>
						<td>회원가입일</td>
						<td>활동지역</td>
						<td>권한</td>
					</tr>
					<tr>
						<td>회원번호</td>
						<td>이름</td>
						<td>아이디</td>
						<td>비밀번호</td>
						<td>닉네임</td>
						<td>나이</td>
						<td>성별</td>
						<td>이메일</td>
						<td>총결제금액</td>
						<td>코인</td>
						<td>이용가능토크</td>
						<td>회원가입일</td>
						<td>활동지역</td>
						<td>권한</td>
					</tr>
					<tr>
						<td>회원번호</td>
						<td>이름</td>
						<td>아이디</td>
						<td>비밀번호</td>
						<td>닉네임</td>
						<td>나이</td>
						<td>성별</td>
						<td>이메일</td>
						<td>총결제금액</td>
						<td>코인</td>
						<td>이용가능토크</td>
						<td>회원가입일</td>
						<td>활동지역</td>
						<td>권한</td>
					</tr>
					<tr>
						<td>회원번호</td>
						<td>이름</td>
						<td>아이디</td>
						<td>비밀번호</td>
						<td>닉네임</td>
						<td>나이</td>
						<td>성별</td>
						<td>이메일</td>
						<td>총결제금액</td>
						<td>코인</td>
						<td>이용가능토크</td>
						<td>회원가입일</td>
						<td>활동지역</td>
						<td>권한</td>
					</tr>
					<tr>
						<td>회원번호</td>
						<td>이름</td>
						<td>아이디</td>
						<td>비밀번호</td>
						<td>닉네임</td>
						<td>나이</td>
						<td>성별</td>
						<td>이메일</td>
						<td>총결제금액</td>
						<td>코인</td>
						<td>이용가능토크</td>
						<td>회원가입일</td>
						<td>활동지역</td>
						<td>권한</td>
					</tr>
					<tr>
						<td>회원번호</td>
						<td>이름</td>
						<td>아이디</td>
						<td>비밀번호</td>
						<td>닉네임</td>
						<td>나이</td>
						<td>성별</td>
						<td>이메일</td>
						<td>총결제금액</td>
						<td>코인</td>
						<td>이용가능토크</td>
						<td>회원가입일</td>
						<td>활동지역</td>
						<td>권한</td>
					</tr>
					<tr>
						<td>회원번호</td>
						<td>이름</td>
						<td>아이디</td>
						<td>비밀번호</td>
						<td>닉네임</td>
						<td>나이</td>
						<td>성별</td>
						<td>이메일</td>
						<td>총결제금액</td>
						<td>코인</td>
						<td>이용가능토크</td>
						<td>회원가입일</td>
						<td>활동지역</td>
						<td>권한</td>
					</tr>
					<tr>
						<td>회원번호</td>
						<td>이름</td>
						<td>아이디</td>
						<td>비밀번호</td>
						<td>닉네임</td>
						<td>나이</td>
						<td>성별</td>
						<td>이메일</td>
						<td>총결제금액</td>
						<td>코인</td>
						<td>이용가능토크</td>
						<td>회원가입일</td>
						<td>활동지역</td>
						<td>권한</td>
					</tr>
					<tr>
						<td>회원번호</td>
						<td>이름</td>
						<td>아이디</td>
						<td>비밀번호</td>
						<td>닉네임</td>
						<td>나이</td>
						<td>성별</td>
						<td>이메일</td>
						<td>총결제금액</td>
						<td>코인</td>
						<td>이용가능토크</td>
						<td>회원가입일</td>
						<td>활동지역</td>
						<td>권한</td>
					</tr>
					<tr>
						<td>회원번호</td>
						<td>이름</td>
						<td>아이디</td>
						<td>비밀번호</td>
						<td>닉네임</td>
						<td>나이</td>
						<td>성별</td>
						<td>이메일</td>
						<td>총결제금액</td>
						<td>코인</td>
						<td>이용가능토크</td>
						<td>회원가입일</td>
						<td>활동지역</td>
						<td>권한</td>
					</tr>
					<tr>
						<td>회원번호</td>
						<td>이름</td>
						<td>아이디</td>
						<td>비밀번호</td>
						<td>닉네임</td>
						<td>나이</td>
						<td>성별</td>
						<td>이메일</td>
						<td>총결제금액</td>
						<td>코인</td>
						<td>이용가능토크</td>
						<td>회원가입일</td>
						<td>활동지역</td>
						<td>권한</td>
					</tr>
					<tr>
						<td>회원번호</td>
						<td>이름</td>
						<td>아이디</td>
						<td>비밀번호</td>
						<td>닉네임</td>
						<td>나이</td>
						<td>성별</td>
						<td>이메일</td>
						<td>총결제금액</td>
						<td>코인</td>
						<td>이용가능토크</td>
						<td>회원가입일</td>
						<td>활동지역</td>
						<td>권한</td>
					</tr>
					<tr>
						<td>회원번호</td>
						<td>이름</td>
						<td>아이디</td>
						<td>비밀번호</td>
						<td>닉네임</td>
						<td>나이</td>
						<td>성별</td>
						<td>이메일</td>
						<td>총결제금액</td>
						<td>코인</td>
						<td>이용가능토크</td>
						<td>회원가입일</td>
						<td>활동지역</td>
						<td>권한</td>
					</tr>
					<tr>
						<td>회원번호</td>
						<td>이름</td>
						<td>아이디</td>
						<td>비밀번호</td>
						<td>닉네임</td>
						<td>나이</td>
						<td>성별</td>
						<td>이메일</td>
						<td>총결제금액</td>
						<td>코인</td>
						<td>이용가능토크</td>
						<td>회원가입일</td>
						<td>활동지역</td>
						<td>권한</td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
	<script type="text/javascript" src="/js/manager/search.js"></script>
	<%-- <%@ include file="../../layout/footer.jsp"%> --%>
</body>
</html>